services:
  db:
    image: timescale/timescaledb:latest-pg16-oss
    container_name: fintrend-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrend
    volumes:
      - ../../docker-data/db:/var/lib/postgresql/data
      - ../../backend/storage/sql:/sql:ro

  redis:
    image: redis:7
    container_name: fintrend-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    image: python:3.11-slim
    container_name: fintrend-api
    working_dir: /app
    command: bash -lc "pip install fastapi uvicorn prometheus-client psycopg2-binary && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:20
    container_name: fintrend-frontend
    working_dir: /app
    command: bash -lc "npm install --silent && npm run dev -- --host 0.0.0.0 --port 5180"
    volumes:
      - ../../frontend:/app
    ports:
      - "5180:5180"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    container_name: fintrend-prometheus
    volumes:
      - ../../infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: fintrend-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
  
  # Defines new services for RSS producer, Reddit producer, and news worker.
  producer_rss:
    image: python:3.11-slim
    container_name: fintrend-producer-rss
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir feedparser redis && python -m ingestors.rss_producer"
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    depends_on:
      - redis

  producer_reddit:
    image: python:3.11-slim
    container_name: fintrend-producer-reddit
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir requests feedparser redis && python -m ingestors.reddit_producer"
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    depends_on:
      - redis

  worker_news:
    image: python:3.11-slim
    container_name: fintrend-worker-news
    working_dir: /app
    command: bash -lc "pip install --no-cache-dir redis psycopg2-binary prometheus-client && python -m workers.news_consumer"
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    depends_on:
      - db
      - redis
    ports:
      - "9101:9101"   # expose Prometheus metrics to host
  
  worker_sentiment:
    image: python:3.11-slim
    container_name: fintrend-worker-sentiment
    working_dir: /app
    command:
      - bash
      - -lc
      - pip install --no-cache-dir torch transformers redis psycopg2-binary prometheus-client && python -m workers.sentiment_consumer
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@db:5432/fintrend
      REDIS_URL: redis://redis:6379/0
      LOG_LEVEL: INFO
      HF_HOME: /models
      PYTHONPATH: /app            # ensure /app is on import path
    depends_on:
      db:
        condition: service_started
        required: true
      redis:
        condition: service_started
        required: true
    ports:
      - "9102:9102"
    volumes:
      - type: bind
        source: /Users/abhiramnambiar/Desktop/Abhiram/fintrend-ai/backend
        target: /app
        bind:
          create_host_path: true
      - type: bind
        source: /Users/abhiramnambiar/Desktop/Abhiram/fintrend-ai/docker-data/hf
        target: /models
        bind:
          create_host_path: true

