version: "3.9"

services:
  db:
    image: timescale/timescaledb:pg16-latest
    container_name: fintrend-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrend
    ports:
      - "5432:5432"
    volumes:
      - ./../prometheus/.keep:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fintrend-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: ../../backend
    container_name: fintrend-api
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    build: ../../frontend
    container_name: fintrend-frontend
    command: ["npm","run","dev","--","--host","0.0.0.0","--port","5180"]
    volumes:
      - ../../frontend:/app
    ports:
      - "5180:5180"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    container_name: fintrend-prometheus
    volumes:
      - ../prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: fintrend-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
