services:
  db:
    image: timescale/timescaledb:latest-pg16-oss
    container_name: fintrend-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fintrend
    volumes:
      - ../../docker-data/db:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: fintrend-redis
    restart: always
    ports:
      - "6379:6379"

  api:
    image: python:3.11-slim
    container_name: fintrend-api
    working_dir: /app
    command: bash -lc "pip install fastapi uvicorn prometheus-client && uvicorn api.main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ../../backend:/app
    env_file:
      - ../../.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis

  frontend:
    image: node:20
    container_name: fintrend-frontend
    working_dir: /app
    command: bash -lc "npm install --silent && npm run dev -- --host 0.0.0.0 --port 5180"
    volumes:
      - ../../frontend:/app
    ports:
      - "5180:5180"
    depends_on:
      - api

  prometheus:
    image: prom/prometheus
    container_name: fintrend-prometheus
    volumes:
      - ../../infra/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    container_name: fintrend-grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
